# Generated by Django 2.2.4 on 2019-08-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
